services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "${APP_PORT:-5173}:${APP_PORT:-5173}"
    volumes:
      - .:/app
    environment:
      - ENV=${ENV:-dev}
      - JWT_SECRET=${JWT_SECRET}
      # 设置 Bun 镜像源
      - BUN_INSTALL_REGISTRY=https://registry.npmmirror.com
      - BUN_INSTALL_GLOBAL_CACHE=/app/.bun/install/global
      - BUN_INSTALL_CACHE=/app/.bun/install/cache
      # MySQL 连接配置
      - MYSQL_URL=${MYSQL_URL}
    command: >
      sh -c "
        echo 'Environment: $${ENV:-dev}' &&
        rm -rf node_modules bun.lock &&
        bun pm cache clear &&
        bun pm cache rm &&
        bun install &&
        if [ \"$${ENV:-dev}\" = \"prod\" ]; then
          echo 'Starting prod mode...' &&
          bun run build &&
          bun run start
        else
          echo 'Starting dev mode...' &&
          bun run dev
        fi
      "
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
